const express = require('express');
const authRoutes = require('./authRoutes');
const userRoutes = require('./userRoutes');
const catalogRoutes = require('./catalogRoutes');
const applicationRoutes = require('./applicationRoutes');
const paymentRoutes = require('./paymentRoutes');
const taskRoutes = require('./taskRoutes');
const rbacRoutes = require('./rbacRoutes');
const ticketRoutes = require('./ticketRoutes');
const notificationRoutes = require('./notificationRoutes');
const emailTemplateRoutes = require('./emailTemplateRoutes');
const ceoDashboardRoutes = require('./ceoDashboardRoutes');
const dynamicFormRoutes = require('./dynamicFormRoutes');
const schedulerRoutes = require('./schedulerRoutes');
const agentTargetRoutes = require('./agentTargetRoutes');
const calendarRoutes = require('./calendarRoutes');
const campaignRoutes = require('./campaignRoutes');
const sequenceRoutes = require('./sequenceRoutes');
const mailboxRoutes = require('./mailboxRoutes');
const documentFeedbackRoutes = require('./documentFeedbackRoutes');
const chatRoutes = require('./chatRoutes');
const callLogRoutes = require('./callLogRoutes');
const callScorecardRoutes = require('./callScorecardRoutes');
const callBurstRoutes = require('./callBurstRoutes');
const twilioVoiceRoutes = require('./webhooks/twilioVoiceRoutes');
const rtoInvoiceRoutes = require('./rtoInvoiceRoutes');
const chatbotRoutes = require('./chatbotRoutes');
const competencyBookingRoutes = require('./competencyBookingRoutes');
const paymentBatchRoutes = require('./paymentBatchRoutes');
const xeroRoutes = require('./xeroRoutes');
const searchRoutes = require('./searchRoutes');
const guardrailRoutes = require('./guardrailRoutes');
const directDebitAuthRoutes = require('./directDebitAuthRoutes');
const applicationController = require('../controllers/applicationController');
const { protect } = require('../middleware/auth');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/', catalogRoutes);
router.use('/applications', applicationRoutes);
router.use('/payments', paymentRoutes);
router.use('/tasks', taskRoutes);
router.use('/rbac', rbacRoutes);
router.use('/tickets', ticketRoutes);
router.use('/notifications', notificationRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/ceo-dashboard', ceoDashboardRoutes);
router.use('/dynamic-forms', dynamicFormRoutes);
router.use('/scheduler', schedulerRoutes);
router.use('/agent-targets', agentTargetRoutes);
router.use('/calendar', calendarRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/sequences', sequenceRoutes);
router.use('/mailboxes', mailboxRoutes);
router.use('/document-feedback', documentFeedbackRoutes);
router.use('/chat', chatRoutes);
router.use('/call-logs', callLogRoutes);
router.use('/call-scorecard', callScorecardRoutes);
router.use('/calls', callBurstRoutes);
// Public Twilio Voice webhooks (signature-validated in the controller)
router.use('/webhooks/twilio', twilioVoiceRoutes);
router.use('/rto-invoices', rtoInvoiceRoutes);
router.use('/chatbot', chatbotRoutes);
router.use('/competency-bookings', competencyBookingRoutes);
router.use('/payment-batches', paymentBatchRoutes);
router.use('/xero', xeroRoutes);
router.use('/search', searchRoutes);
router.use('/guardrails', guardrailRoutes);
router.use('/direct-debit-auth', directDebitAuthRoutes);

// Standalone intake form access (read-only, authenticated — exposes applicant PII)
router.get('/intake-forms/:id', protect, applicationController.intakeForms.getById);

module.exports = router;
