'use strict';

const PDFDocument = require('pdfkit');

/**
 * Generate a branded Student Intake Form PDF from IntakeForm data.
 * Matches the old portal's PDF layout exactly (pdfkit with continued text pattern).
 *
 * @param {Object} data — IntakeForm document (lean), uses new v2 field names
 * @param {string} applicationId — e.g. "APP29750"
 * @param {string} qualificationName — qualification display name
 * @returns {Promise<Buffer>}
 */
const generateStudentIntakePdf = async (data, applicationId, qualificationName) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);

      // Header
      doc.fontSize(20)
        .fillColor('#089C34')
        .text('Student Intake Form', { align: 'center' });

      doc.moveDown();
      doc.fontSize(12)
        .fillColor('#666666')
        .text(`Application ID: ${applicationId}`, { align: 'center' });

      if (qualificationName) {
        doc.fontSize(10)
          .fillColor('#666666')
          .text(qualificationName, { align: 'center' });
      }

      doc.moveDown(2);

      // Helper function to add section
      const addSection = (title) => {
        doc.fontSize(14)
          .fillColor('#089C34')
          .text(title, { underline: true });
        doc.moveDown(0.5);
      };

      // Helper function to add field — uses { continued: true } so label + value stay on same line
      const addField = (label, value) => {
        doc.fontSize(10)
          .fillColor('#000000')
          .text(label, { continued: true, width: 200 })
          .fillColor('#333333')
          .text(`: ${value || 'N/A'}`);
        doc.moveDown(0.3);
      };

      // Personal Information
      addSection('Personal Information');
      addField('First Name', data.firstName);
      addField('Middle Name', data.middleName);
      addField('Last Name', data.surname);
      addField('Date of Birth', data.dateOfBirth ? new Date(data.dateOfBirth).toLocaleDateString('en-AU') : null);
      addField('Gender', data.gender);
      addField('USI', data.usi);
      doc.moveDown();

      // Contact Information
      addSection('Contact Information');
      addField('Email', data.email);
      addField('Contact Number', data.phoneNumber);
      addField('Home Address', data.streetAddress);
      addField('Suburb', data.suburb);
      addField('Postcode', data.postcode);
      addField('State', data.state);
      doc.moveDown();

      // Background Information
      addSection('Background Information');
      addField('Country of Birth', data.countryOfBirth);
      addField('Australian Citizen', data.isAustralianCitizen === true ? 'Yes' : data.isAustralianCitizen === false ? 'No' : null);
      addField('Aboriginal or Torres Strait Islander', data.isAboriginalOrTorresStrait === true ? 'Yes' : data.isAboriginalOrTorresStrait === false ? 'No' : null);
      addField('English Level', data.englishLevel);
      addField('Disability', data.hasDisability === true ? 'Yes' : data.hasDisability === false ? 'No' : null);
      doc.moveDown();

      // Education Information
      addSection('Education Information');
      addField('Previous Qualifications', data.previousQualifications);
      addField('Credits Transfer', data.hasCreditToTransfer ? 'Yes' : 'No');
      if (data.hasCreditToTransfer) {
        addField('Name of Qualification', data.creditQualificationName);
        addField('Year Completed', data.creditYearCompleted);
      }
      doc.moveDown();

      // Employment Information
      addSection('Employment Information');
      addField('Employment Status', data.employmentStatus);
      if (data.businessName) {
        addField('Business Name', data.businessName);
        addField('Position', data.position);
        addField("Employer's Legal Name", data.employerLegalName);
        addField("Employer's Address", data.employerAddress);
        addField("Employer's Contact Number", data.employerPhone);
      }
      doc.moveDown();

      // Declaration
      if (data.submittedAt) {
        addSection('Declaration');
        addField('Submitted', 'Yes');
        addField('Date', new Date(data.submittedAt).toLocaleDateString('en-AU'));
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(8)
        .fillColor('#999999')
        .text('This document was generated by Certified Australia', { align: 'center' });
      doc.text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = generateStudentIntakePdf;
